services:
  broker_a:
    image: eclipse-mosquitto:latest
    container_name: broker_a
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto:/mosquitto
    networks:
      - pubsub-net

  broker_b:
    image: eclipse-mosquitto:latest
    container_name: broker_b
    ports:
      - "1884:1883"
    volumes:
      - ./mosquitto:/mosquitto
    networks:
      - pubsub-net

networks:
  pubsub-net:
    driver: bridge
